SEO-176062-Aurelia-controls-issue-fixes
syncfusion-content/aurelia-docs pull request #213
Opened 2023-09-21 10:12 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-21 10:13 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-176062-Aurelia-controls-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/aurelia-docs/1461/console)**

2023-09-21 10:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176062-Aurelia-controls-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/aurelia-docs/1461/console)**

2023-09-21 10:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Aurelia-controls-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/aurelia-docs/1461/)<br/>**

2023-09-28 08:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176062-Aurelia-controls-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/aurelia-docs/1468/)<br/>**

2023-10-05 08:46 UTC, Yvone-Atieno requested changes
Commented

2023-10-05 08:46 UTC, Yvone-Atieno commented on Aurelia/Maps/Getting-Started.md
> +* [jQuery](https://jquery.com) version  1.10.1 and above,
Revert this change

2023-10-10 16:33 UTC, Edithabich commented on Aurelia/Maps/Getting-Started.md
> +* [jQuery](https://jquery.com) version  1.10.1 and above,
resolved

2023-10-17 07:17 UTC, Yvone-Atieno approved these changes
Approved

2023-11-01 12:04 UTC, Aishwarya-Ganesan approved these changes
fine.

2023-11-01 12:04 UTC, merged